name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: '🚀 新機能'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 不具合修正'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 メンテナンス'
    labels:
      - 'chore'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'exclude-changelog'
template: |
  # v$NEXT_MINOR_VERSION

   ## 変更点

   $CHANGES